// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: generate.proto

package testdata

import (
	"reflect"
	"sync"

	"github.com/golang/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BlankMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlankMsg) Reset() {
	*x = BlankMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlankMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlankMsg) ProtoMessage() {}

func (x *BlankMsg) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlankMsg.ProtoReflect.Descriptor instead.
func (*BlankMsg) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{1}
}

var File_generate_proto protoreflect.FileDescriptor

var file_generate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x19, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0a, 0x0a, 0x08, 0x62,
	0x6c, 0x61, 0x6e, 0x6b, 0x4d, 0x73, 0x67, 0x32, 0x4c, 0x0a, 0x03, 0x66, 0x6f, 0x6f, 0x12, 0x11,
	0x0a, 0x03, 0x62, 0x61, 0x72, 0x12, 0x04, 0x2e, 0x6d, 0x73, 0x67, 0x1a, 0x04, 0x2e, 0x6d, 0x73,
	0x67, 0x12, 0x13, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x04, 0x2e, 0x6d, 0x73, 0x67,
	0x1a, 0x04, 0x2e, 0x6d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x05, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x12,
	0x09, 0x2e, 0x62, 0x6c, 0x61, 0x6e, 0x6b, 0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e, 0x62, 0x6c, 0x61,
	0x6e, 0x6b, 0x4d, 0x73, 0x67, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generate_proto_rawDescOnce sync.Once
	file_generate_proto_rawDescData = file_generate_proto_rawDesc
)

func file_generate_proto_rawDescGZIP() []byte {
	file_generate_proto_rawDescOnce.Do(func() {
		file_generate_proto_rawDescData = protoimpl.X.CompressGZIP(file_generate_proto_rawDescData)
	})
	return file_generate_proto_rawDescData
}

var file_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generate_proto_goTypes = []interface{}{
	(*Msg)(nil),      // 0: msg
	(*BlankMsg)(nil), // 1: blankMsg
}
var file_generate_proto_depIdxs = []int32{
	0, // 0: foo.bar:input_type -> msg
	0, // 1: foo.error:input_type -> msg
	1, // 2: foo.blank:input_type -> blankMsg
	0, // 3: foo.bar:output_type -> msg
	0, // 4: foo.error:output_type -> msg
	1, // 5: foo.blank:output_type -> blankMsg
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generate_proto_init() }
func file_generate_proto_init() {
	if File_generate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_generate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlankMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_goTypes,
		DependencyIndexes: file_generate_proto_depIdxs,
		MessageInfos:      file_generate_proto_msgTypes,
	}.Build()
	File_generate_proto = out.File
	file_generate_proto_rawDesc = nil
	file_generate_proto_goTypes = nil
	file_generate_proto_depIdxs = nil
}
